### ISSUE TITLE
Make SRP the default AuthN mechanism

### ISSUE THREAD

**Issue by undefobj** [awslabs/realworld-serverless-application#50]
USER_PASSWORD_AUTH is set in this project: https://github.com/awslabs/realworld-serverless-application/blob/30a2cf044fb77c2ea0faf69d33a26281e2ab5480/static-website/src/config.js#L12

This shouldn't be used by default as it's used mostly for migrations and SRP should be the default which Amplify uses. I recommend removing this.

**Comment by jlhood** [comment]
Thanks for reporting this, @undefobj!

**Comment by honglu** [comment]
The fix has been merged
